Added login/register form on the page, and added couse and mypage.
RajendraBhagroo/TeleQuest pull request #18
Opened 2019-03-10 06:09 UTC by Gold-Turtle

2019-03-10 06:26 UTC, RajendraBhagroo requested changes

2019-03-10 06:26 UTC, RajendraBhagroo commented on config/.env.example
> -# Shared
@Gold-Turtle ,

Please create this file under config/.env.example. In this pull request you have deleted this entire file, we need this file so other developers can refer to it to properly create their own config.

2019-03-10 06:30 UTC, RajendraBhagroo requested changes

2019-03-10 06:30 UTC, RajendraBhagroo commented on client/src/redux/actions/authAction.js
> +
@Gold-Turtle ,

Nice, remember what we spoke about just now on discord. Research redux-thunk & axios. Axios is how we will communicate with our server. Redux-Thunk allows us to return functions from actions. The returned function will execute, make the axios call, and then return us the object [type & payload] to be processed to our reducer.

2019-03-14 18:33 UTC, RajendraBhagroo approved these changes

2019-03-14 19:42 UTC, gint0kix approved these changes
Approved

2019-03-14 20:14 UTC, merged